# Generated by Django 5.2.8 on 2026-01-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_tasklist_user_alter_tasklist_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='user',
        ),
    ]
