# Generated by Django 5.2.8 on 2026-01-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_alter_tasklist_priority_alter_tasklist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
    ]
